### ISSUE TITLE
Cooperation possiblities

### ISSUE THREAD

**Issue by wickywaka** [triveme/smartcity-dashboard#7]
Hi everybody,
Probably not the right place to write this here but I don't know any other options of reaching the technical team.

I am the technical co-founder of SpotTroop and would like to see if there are possibilities for us to cooperate together.
Although we are private company but are open to collaborate on open source projects to help cities manage their parking spaces in a better way.

Hope to hear back from you soon.

Waqar Rashid

**Comment by Severon96** [comment]
Hey @wickywaka you can contact us via suessemilch@trive.me ! 😊

**Comment by asuessemilch** [comment]
I have nothing heard yet ;) Feel free to contact me as Dominik had described, or via LinkedIn: https://www.linkedin.com/in/asuessemilch/

**Comment by wickywaka** [comment]
Its still on my todo. Will contact you when I have enough time to actually
look at the code.

**Comment by wickywaka** [comment]
> I have nothing heard yet ;) Feel free to contact me as Dominik had described, or via LinkedIn: https://www.linkedin.com/in/asuessemilch/

@asuessemilch I sent you request on LinkedIn

**Comment by wickywaka** [comment]
How do you get the data from KielRegion? Do they have to give me some api access?

**Comment by Severon96** [comment]
hello @wickywaka 
KielRegion has it's own instance of the dashboard, hosted on their infrastructure. They configure it by themself to access their fiware services.
It don't believe it will be possible for you to get access to their api.
